from tkinter import *
import library_arbeitsvertrag as la
import os
from datetime import datetime


mitarbeiterdaten = la.vertragsdaten
def generate_pdf_from_entries():   
    mitarbeiterdaten['arbeitgeber'] = arbeitgeber_entry.get()
    mitarbeiterdaten['vertreter'] = vertreter_entry.get()
    mitarbeiterdaten['vorname'] = vorname_entry.get()
    mitarbeiterdaten['nachname'] = nachname_entry.get()
    mitarbeiterdaten['geburtstag'] = geburtstag_entry.get()
    mitarbeiterdaten['geburtsort'] = geburtsort_entry.get()
    mitarbeiterdaten['maanschriftSTR'] = maanschriftStr_entry.get()
    mitarbeiterdaten['maanschriftNr'] = maanschriftNr_entry.get()
    mitarbeiterdaten['maanschriftPLZ'] = maanschriftPLZ_entry.get()
    mitarbeiterdaten['maanschriftStadt'] = maanschriftStadt_entry.get()
    mitarbeiterdaten['krankenversicherung'] = krankenversicherung_entry.get()
    mitarbeiterdaten['rentenversicherungsnummer'] = rentenversicherungsnummer_entry.get()
    mitarbeiterdaten['konfession'] = konfession_entry.get()
    mitarbeiterdaten['steuerklasse'] = steuerklasse_entry.get()
    mitarbeiterdaten['kontoInstitut'] = kontoInstitut_entry.get()
    mitarbeiterdaten['kontoIBAN'] = kontoIBAN_entry.get()
    mitarbeiterdaten['kontoBIC'] = kontoBIC_entry.get()
    mitarbeiterdaten['stunden'] = stunden_entry.get()
    mitarbeiterdaten['arbeitszeitBeginn'] = arbeitszeitBeginn_entry.get()
    mitarbeiterdaten['arbeitszeitEnde'] = arbeitszeitEnde_entry.get()
    mitarbeiterdaten['beginn'] = beginn_entry.get()
    mitarbeiterdaten['stellenbezeichnung'] = stellenbezeichnung_entry.get()
    mitarbeiterdaten['aufgabe'] = aufgabe_entry.get()
    mitarbeiterdaten['urlaub'] = urlaub_entry.get()
    mitarbeiterdaten['pauschal'] = pauschal_entry.get()
    mitarbeiterdaten['rente'] = rente_entry.get()
    mitarbeiterdaten['lohn'] = lohn_entry.get()

    la.write_dict_to_configfile(inputdict=mitarbeiterdaten, outputfile='texdata/lat.tex')
    filename = str(mitarbeiterdaten['nachname']) + str(datetime.today().strftime('%Y-%m-%d'))
    os.system("pdflatex --jobname=" + filename + " texdata/main.tex")
    os.system("open "+ filename + ".pdf")
    os.system("rm *.log *.aux")

master = Tk()
master.title('Arbeitsvertrag')

Label(master, name="arbeitgeber", text="Arbeitgeber").grid(row=0)
Label(master, name="vertreter", text="Vertreter").grid(row=1)
Label(master, name="vorname", text="Vorname").grid(row=2)
Label(master, name="nachname", text="Nachname").grid(row=3)
Label(master, name="geburtstag", text="Geburtstag").grid(row=4)
Label(master, name="geburtsort", text="Geburtsort").grid(row=5)
Label(master, name="maanschriftStr", text="MAAnschriftStr").grid(row=6)
Label(master, name="maanschriftNr", text="MAAnschriftNr").grid(row=7)
Label(master, name="maanschriftPLZ", text="MAAnschriftPLZ").grid(row=8)
Label(master, name="maanschriftStadt", text="MAAnschriftStadt").grid(row=9)
Label(master, name="krankenversicherung", text="Krankenversicherung").grid(row=10)
Label(master, name="rentenversicherungsnummer", text="Rentenversicherungsnummer").grid(row=11)
Label(master, name="konfession", text="Konfession").grid(row=12)
Label(master, name="steuerklasse", text="Steuerklasse").grid(row=13)
Label(master, name="kontoInstitut", text="KontoInstitut").grid(row=14)
Label(master, name="kontoIBAN", text="KontoIBAN").grid(row=15)
Label(master, name="kontoBIC", text="KontoBIC").grid(row=16)
Label(master, name="stunden", text="Stunden").grid(row=17)
Label(master, name="arbeitszeitBeginn", text="ArbeitszeitBeginn").grid(row=18)
Label(master, name="arbeitszeitEnde", text="ArbeitszeitEnde").grid(row=19)
Label(master, name="beginn", text="Beginn").grid(row=20)
Label(master, name="stellenbezeichnung", text="Stellenbezeichnung").grid(row=21)
Label(master, name="aufgabe", text="Aufgabe").grid(row=22)
Label(master, name="urlaub", text="Urlaub").grid(row=23)
Label(master, name="pauschal", text="Pauschal").grid(row=24)
Label(master, name="rente", text="Rente").grid(row=25)
Label(master, name="lohn", text="Lohn").grid(row=26)


arbeitgeber_entry = Entry(master)
vertreter_entry = Entry(master)
vorname_entry = Entry(master)
nachname_entry = Entry(master)
geburtstag_entry = Entry(master)
geburtsort_entry = Entry(master)
maanschriftStr_entry = Entry(master)
maanschriftNr_entry = Entry(master)
maanschriftPLZ_entry = Entry(master)
maanschriftStadt_entry = Entry(master)
krankenversicherung_entry = Entry(master)
rentenversicherungsnummer_entry = Entry(master)
konfession_entry = Entry(master)
steuerklasse_entry = Entry(master)
kontoInstitut_entry = Entry(master)
kontoIBAN_entry = Entry(master)
kontoBIC_entry = Entry(master)
stunden_entry = Entry(master)
arbeitszeitBeginn_entry = Entry(master)
arbeitszeitEnde_entry = Entry(master)
beginn_entry = Entry(master)
stellenbezeichnung_entry = Entry(master)
urlaub_entry = Entry(master)
aufgabe_entry = Entry(master)
pauschal_entry = Entry(master)
rente_entry = Entry(master)
lohn_entry = Entry(master)

arbeitgeber_entry.grid(row=0, column=1)
vertreter_entry.grid(row=1, column=1)
vorname_entry.grid(row=2, column=1)
nachname_entry.grid(row=3, column=1)
geburtstag_entry.grid(row=4, column=1)
geburtsort_entry.grid(row=5, column=1)
maanschriftStr_entry.grid(row=6, column=1)
maanschriftNr_entry.grid(row=7, column=1)
maanschriftPLZ_entry.grid(row=8, column=1)
maanschriftStadt_entry.grid(row=9, column=1)
krankenversicherung_entry.grid(row=10, column=1)
rentenversicherungsnummer_entry.grid(row=11, column=1)
konfession_entry.grid(row=12, column=1)
steuerklasse_entry.grid(row=13, column=1)
kontoInstitut_entry.grid(row=14, column=1)
kontoIBAN_entry.grid(row=15, column=1)
kontoBIC_entry.grid(row=16, column=1)
stunden_entry.grid(row=17, column=1)
arbeitszeitBeginn_entry.grid(row=18, column=1)
arbeitszeitEnde_entry.grid(row=19, column=1)
beginn_entry.grid(row=20, column=1)
stellenbezeichnung_entry.grid(row=21, column=1)
urlaub_entry.grid(row=22, column=1)
aufgabe_entry.grid(row=23, column=1)
pauschal_entry.grid(row=24, column=1)
rente_entry.grid(row=25, column=1)
lohn_entry.grid(row=26, column=1)



Button(master, text='Erstelle PDF', command=generate_pdf_from_entries).grid(row=29, column=4, sticky=W, pady=4)
Button(master, text='Beenden', command=master.quit).grid(row=29, column=6, sticky=W, pady=4)

mainloop( )